# Generated by Django 5.1 on 2024-08-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grade_student_grades_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=9),
        ),
    ]
